### ISSUE TITLE
Italic button not working

### ISSUE THREAD

**Issue by NetSecond** [widgetfactory/jce#93] opened 2021-06-15 11:17 UTC
If you click on "I" (italic) in the editor, nothing happens and you cannot continue writing.
The same thing happens in all browsers I tested and even on your demo page.
All other buttons works fine.

**Comment by ryandemmer** [comment] 2021-06-15 11:28
I"m not able to reproduce this issue on the demo site with Firefox and Chrome. Italic works as expected in both.

**Comment by NetSecond** [comment] 2021-06-15 13:39
I am able to reproduce it on your demo site with edge, firefox, chrome and opera.
And on different own installations with joomla 3.9 and 4.0rc2.

What is the difference between your tests and mine ??
I have tested it with different pcs too.

EDIT:
I tested it a little bit more:
If you write a text, mark it and then press "I" for italics, it is working.
If you write text, press "I" for italics, want to write more, then nothing happens.

If you try the same with bold or underline, you can switch without problems and write more.
Only at italics, you can´t write after switching to italics until you switch to bold or something else.

Example:
you wrote "jkugjhgjhgjhgjhgjhg" and then switch to italics and write after that again some chars ....

It looks like, that the focus of the italics routine isn´t switch back to text field.

In the forum, I found someone else with that problem, but no solution.
There was at least the question after the problem at special extension or everywhere.
The poster din´t answer til now.
But this problem occours everywhere, like in articles or other extensions.

**Comment by ryandemmer** [comment] 2021-08-31 19:21
Fixed in commit - https://github.com/widgetfactory/jce/commit/cc36da2a2daa426a99b3b68cbd8b4c91984aef98

Thank you.

**Closed as completed** 2021-09-02 14:07 UTC
